### ISSUE TITLE
Validator crash: TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by thomas-riccardi** [Deepomatic/dmake#268]
# Scenario

```
$ cat dmake.yml
dmake_version: 0.1
app_name: test-repro

build: "string instead of object, containing the string 'commands' which' is an expected object key"

docker:
  root_image:
    name: ubuntu
    tag: 18.04

services: []


$ dmake run '*'
===============
REPO : 
BUILD : 0
BRANCH : master
COMMIT_ID : 79f2ffa
===============
Traceback (most recent call last):
  File "/home/thomas/deepomatic/dmake/dmake/dmake", line 75, in <module>
    args.func(args)
  File "/home/thomas/deepomatic/dmake/dmake/core.py", line 644, in make
    load_dmake_file(loaded_files, blacklist, service_providers, service_dependencies, file)
  File "/home/thomas/deepomatic/dmake/dmake/core.py", line 291, in load_dmake_file
    dmake_file = DMakeFile(file, data)
  File "/home/thomas/deepomatic/dmake/dmake/deepobuild.py", line 1313, in __init__
    self._validate_(file, needed_migrations=needed_migrations, data=data)
  File "/home/thomas/deepomatic/dmake/dmake/deepobuild.py", line 1284, in _validate_
    super(DMakeFileSerializer, self)._validate_(file, needed_migrations=needed_migrations, data=data, field_name=field_name)
  File "/home/thomas/deepomatic/dmake/dmake/serializer.py", line 350, in _validate_
    field_name=field_name + ':' + name if field_name else name)
  File "/home/thomas/deepomatic/dmake/dmake/deepobuild.py", line 1261, in _validate_
    super(BuildSerializer, self)._validate_(file, needed_migrations=needed_migrations, data=data, field_name=field_name)
  File "/home/thomas/deepomatic/dmake/dmake/serializer.py", line 349, in _validate_
    data=data[name] if name in data else None,
TypeError: string indices must be integers
```

The issue happens when `data` is a string instead of an object (`ruamel.yaml.comments.CommentedMap` it seems), and expected field `name` is `in data`: is substring.
=> we don't validate that data is an object

Related:
#261 checks for lists and dicts using internal standard methods, which are alas also present on `str`: these tests don't test enough.
Example:
```
$ cat dmake.yml 
dmake_version: 0.1
app_name: test-repro
env:
  default:
    variables: "string instead of dict"


docker:
  root_image:
    name: ubuntu
    tag: 18.04

services: []


$ dmake run '*'
===============
REPO : 
BUILD : 0
BRANCH : master
COMMIT_ID : c0cae80
===============
Traceback (most recent call last):
  File "/home/thomas/deepomatic/dmake/dmake/dmake", line 75, in <module>
    args.func(args)
  File "/home/thomas/deepomatic/dmake/dmake/core.py", line 644, in make
    load_dmake_file(loaded_files, blacklist, service_providers, service_dependencies, file)
  File "/home/thomas/deepomatic/dmake/dmake/core.py", line 291, in load_dmake_file
    dmake_file = DMakeFile(file, data)
  File "/home/thomas/deepomatic/dmake/dmake/deepobuild.py", line 1313, in __init__
    self._validate_(file, needed_migrations=needed_migrations, data=data)
  File "/home/thomas/deepomatic/dmake/dmake/deepobuild.py", line 1284, in _validate_
    super(DMakeFileSerializer, self)._validate_(file, needed_migrations=needed_migrations, data=data, field_name=field_name)
  File "/home/thomas/deepomatic/dmake/dmake/serializer.py", line 351, in _validate_
    field_name=field_name + ':' + name if field_name else name)
  File "/home/thomas/deepomatic/dmake/dmake/serializer.py", line 91, in _validate_
    validated_data = t._validate_(file, needed_migrations=needed_migrations, data=data, field_name=field_name)
  File "/home/thomas/deepomatic/dmake/dmake/serializer.py", line 351, in _validate_
    field_name=field_name + ':' + name if field_name else name)
  File "/home/thomas/deepomatic/dmake/dmake/serializer.py", line 351, in _validate_
    field_name=field_name + ':' + name if field_name else name)
  File "/home/thomas/deepomatic/dmake/dmake/serializer.py", line 99, in _validate_
    validated_data = self._validate_type_(file, needed_migrations=needed_migrations, data_type=t, data=data, field_name=field_name)
  File "/home/thomas/deepomatic/dmake/dmake/serializer.py", line 197, in _validate_type_
    for k, d in data.items():
AttributeError: 'str' object has no attribute 'items'
```

We probably will have to use the ruaml types to check for proper type.

**Comment by thomas-riccardi** [comment]
Also reproduced this same error in a different scenario: base_image is either a v1 dockerBase or an array of v2 dockerBase, and we wrongly accept a v1 dockerBase (`ordereddict`, <class 'ruamel.yaml.comments.CommentedMap'>) as an array, because the check for array is `hasattr(data, '__iter__')`. Alas, ordered dicts also have `__iter__`.

This all started to happen since ruamel.yaml 0.15.60 in cb4e58b for python 3.7 support, which changed the base classes of ordered dict and seq, breaking our previously reasonable type check. It has since been reverted back in 0.15.70. Let's use that.
