### ISSUE TITLE
Cleaning up containers when KeyboardInterrupt on a readiness probe

### ISSUE THREAD

**Issue by maingoh** [Deepomatic/dmake#378]
When a readiness probe is in an infinite loop state and we stop it with ctrl + C dmake doesn't ask to cleanup the running containers.

```
Running readiness probe
ls: cannot access '/tmp/worker-nn-ready': No such file or directory
^CTraceback (most recent call last):
  File "/home/hugo/deepomatic/dmake/dmake/dmake", line 116, in <module>
    args.func(args)
  File "/home/hugo/deepomatic/dmake/dmake/core.py", line 894, in make
    result = subprocess.call('bash %s' % file_to_generate, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 1099, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 125, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```

**Comment by thomas-riccardi** [comment]
# How
- handle process signals:
  - forward it to bash subprocess? or just kill it?
  - then call `dmake_cleanup`

Related code: https://github.com/Deepomatic/dmake/blob/5e1b8b36a2fa369421b1672278b6aec5363dc3ef/dmake/core.py#L894-L903
