### ISSUE TITLE
dmake installation fails

### ISSUE THREAD

**Issue by vdel** [Deepomatic/dmake#464]
It tried to install dmake on MacOS + Python 3.8 but installation fails when installing `ruamel.yaml==0.15.71`:

```
pip install ruamel.yaml==0.15.71
Collecting ruamel.yaml==0.15.71
  Using cached ruamel.yaml-0.15.71.tar.gz (309 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python@3.8/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/fb/qmt2vtz96_38tm4c1k0d85br0000gn/T/pip-install-5yqe71d3/ruamel.yaml/setup.py'"'"'; __file__='"'"'/private/var/folders/fb/qmt2vtz96_38tm4c1k0d85br0000gn/T/pip-install-5yqe71d3/ruamel.yaml/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/fb/qmt2vtz96_38tm4c1k0d85br0000gn/T/pip-pip-egg-info-7qj2_yc6
         cwd: /private/var/folders/fb/qmt2vtz96_38tm4c1k0d85br0000gn/T/pip-install-5yqe71d3/ruamel.yaml/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/fb/qmt2vtz96_38tm4c1k0d85br0000gn/T/pip-install-5yqe71d3/ruamel.yaml/setup.py", line 211, in <module>
        pkg_data = _package_data(__file__.replace('setup.py', '__init__.py'))
      File "/private/var/folders/fb/qmt2vtz96_38tm4c1k0d85br0000gn/T/pip-install-5yqe71d3/ruamel.yaml/setup.py", line 184, in _package_data
        data = literal_eval("".join(lines))
      File "/private/var/folders/fb/qmt2vtz96_38tm4c1k0d85br0000gn/T/pip-install-5yqe71d3/ruamel.yaml/setup.py", line 156, in literal_eval
        return _convert(node_or_string)
      File "/private/var/folders/fb/qmt2vtz96_38tm4c1k0d85br0000gn/T/pip-install-5yqe71d3/ruamel.yaml/setup.py", line 95, in _convert
        if isinstance(node, Str):
    NameError: name 'Str' is not defined
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Things work fine with latest ruamel (0.16.12)

**Comment by vdel** [comment]
My master branch was actually not up-to-date. This problem is already fixed.
